import { Noto_Serif_SC, PT_Mono, Playfair_Display } from "next/font/google";
import localFont from "next/font/local";

/**
 * Дисплейный шрифт макета — «MM9 Prose Antique Cyr» (Version 1.00, декабрь 2019,
 * в копирайте только «Generated by Fontographer 4.1»). Лежит в репозитории как
 * woff2 (20 КБ), кириллица полная.
 *
 * Строчные в нём настоящие, а в макете дисплейным набрано всё прописными —
 * поэтому капс зашит в утилиты `text-display-*` через `text-transform`,
 * а в разметке текст пишем как в Figma («легенда», «кухня»).
 *
 * Лицензия оплачена клиентом.
 */
export const display = localFont({
  src: "./mm9/mm9-prose-antique-cyr.woff2",
  variable: "--font-display",
  display: "swap",
  weight: "400",
  style: "normal",
  fallback: ["Playfair Display", "serif"],
  adjustFontFallback: false,
});

/**
 * Playfair Display Italic — им в макете набрана только подпись в «Легенде»
 * (Figma node 222:2020), заголовки идут дисплейным.
 */
export const note = Playfair_Display({
  subsets: ["latin", "cyrillic"],
  weight: ["400"],
  style: ["italic"],
  variable: "--font-note",
  display: "swap",
  adjustFontFallback: false,
});

/** Интерфейсный моношрифт: навигация, кнопки, подписи (PT Mono 10…18 по макету) */
export const ui = PT_Mono({
  subsets: ["latin", "cyrillic"],
  weight: ["400"],
  variable: "--font-ui",
  display: "swap",
  adjustFontFallback: false,
});

/** Акцент — иероглифы 创意料理 в подвале */
export const accent = Noto_Serif_SC({
  subsets: ["latin"],
  weight: ["300", "400", "900"],
  variable: "--font-accent",
  display: "swap",
  adjustFontFallback: false,
});
